- components/js-api-client/src/core/catalogue.ts
- components/js-api-client/src/core/client.ts
- components/js-api-client/src/core/dump-tenant/createSpecQuery.ts
- components/js-api-client/src/core/dump-tenant/dumper.ts
- components/js-api-client/src/core/massCallClient.ts
- components/js-api-client/src/core/navigation.ts
- components/js-api-client/src/core/search.ts
- components/js-api-client/src/index.ts
- components/js-api-client/src/types/search.ts
- components/js-api-client/tests/search.test.js
This PR allows you to be really asynchronous while using the client, managing the heavy lifting of lifecycle, retry, incremental increase or decrease of the pace etc.
```typescript
import { CrystallizeClient } from '.';
import { createMassCallClient, CrystallizePromise, MassCallClientBatch } from './core/massCallClient';
// call of onBatchDone is not blocking. (no await done internally)
const onBatchDone = async (batch: MassCallClientBatch): Promise<void> => {
console.log(`Batch from ${batch.from} to ${batch.to} Done!`);
};
// call of onFailure is blocking. (await is done internally)
// Return:
//     true: the failure is enqueued for retry (if called)
//     false: the failure is not enqueued. You can retry it right away if you want.
const onFailure = async (
batch: MassCallClientBatch, …
```
> :sparkles: Introducing MassAPICallClient

- components/js-storefrontaware-utils/src/adapters/superfast.server.ts
Export encrypt/decrypt methods to make it easier to just use those in superfast.
Story details: https://app.shortcut.com/crystallize/story/6681
> feat: [sc-6681] Export encrypt/decrypt implementation

- components/js-api-client/src/core/client.ts
- components/js-api-client/src/index.ts
| Branch?       | main / x.y.z |
| Bug fix?      | yes/no       |
| New feature?  | yes/no       |
| BC breaks?    | yes/no       |
| Fixed tickets | #...         |
> Support CRYSTALLIZE_TENANT_ID and export id+identifier into gqp query params

- components/js-api-client/src/core/massCallClient.ts
- components/reactjs-components/src/grid/GridRenderer.tsx
- components/reactjs-components/src/grid/grid-renderer-utils.ts
- components/reactjs-components/src/grid/types.ts
- components/reactjs-components/tests/gridcellposition.test.js
Remove all logic to figure out colIndex and rowIndex.
Some minor type improvements included
> Feature/sc 6890/react component remove the code to get colindex

- components/js-api-client/src/index.ts
Exports the mass call client and types.
> chore(components/js-api-client): export mass call client

- components/node-service-api-request-handlers/package.json
- components/node-service-api-request-handlers/src/index.ts
- components/node-service-api-request-handlers/src/payments/razorpay/client.ts
- components/node-service-api-request-handlers/src/payments/razorpay/handlers.ts
- components/node-service-api-request-handlers/src/payments/razorpay/types.ts
| Branch?       | main / razorpay-payment
| Bug fix?      | yes
| Fixed tickets | #...         |
> add razorpay

- components/reactjs-components/package.json
- components/reactjs-components/src/image/component.tsx
- components/reactjs-components/src/image/types.ts
Allow to pass width and height with higher priority
> feat(reactjs-components): Allow to pass width and height with higher priority

- components/js-api-client/src/core/hydrate.ts
- yarn.lock
| Bug fix?      | no       |
| New feature?  | yes       |
| BC breaks?    | no       |
| Fixed tickets | ...       |
Allow the cart hydrater to (optionally) use the PIM API
> Optionally argument for using PIM api for hydrater

- components/js-api-client/package.json
- components/js-api-client/src/core/hydrate.ts
- components/js-api-client/src/types/product.ts
- components/node-service-api-request-handlers/src/cart/handlers.ts
| Branch?       | main / feature-price-lists
| Bug fix?       | no
| New feature?    | yes
| BC breaks?     | no
| Fixed tickets | [sc-8806]
> price list support

- components/reactjs-components/src/image/component.tsx
- components/reactjs-components/src/image/types.ts
| Branch?       | main / image-component-caption-sizes
| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | [sc-9554]
> caption fixes

- components/reactjs-components/package.json
- components/reactjs-components/src/content-transformer/component.tsx
- components/reactjs-components/src/content-transformer/types.ts
| Branch?       | main / new-text-editor-support
| Fixed tickets | [sc-9815]
> support for new text editor

- components/node-service-api-request-handlers/package.json
- components/node-service-api-request-handlers/src/index.ts
- components/node-service-api-request-handlers/src/payments/adyen/handlers.ts
- components/node-service-api-request-handlers/src/payments/adyen/types.ts
- yarn.lock
| Branch?       | main / feature-adyen-integration
| Fixed tickets | [sc-6548]
> adyen payment integration

- components/node-service-api-request-handlers/package.json
- components/node-service-api-request-handlers/src/payments/adyen/handlers.ts
| Branch?       | main / feature-adyen-integration
| Bug fix?      | yes
| New feature?  | no
> fix cart amount

- components/reactjs-components/package.json
- components/reactjs-components/src/content-transformer/component.tsx
- components/reactjs-components/src/content-transformer/types.ts
| Branch?       | main / feature-table-support
| Fixed tickets | [sc-9815]
> rich-text-table-support

- components/import-export-sdk/package.json
- components/import-export-sdk/src/shape/queries/fragments/shape.ts
- components/js-api-client/package.json
- components/js-api-client/src/core/dump-tenant/createSpecQuery.ts
- components/schema/package.json
- components/schema/src/item/components/itemRelations/index.ts
- components/schema/src/shape/components.ts
- components/schema/tests/shape/itemRelations.test.ts
- components/schema/tests/shape/minMaxValidation.test.ts
| Branch?       | main |
| Bug fix?      | no       |
| New feature?  | yes      |
| BC breaks?    | no       |
| Fixed tickets | #10403        |
> expand schema relitems with minItems maxItems minSkus maxSkus

- components/node-service-api-request-handlers/README.md
- components/node-service-api-request-handlers/package.json
- components/node-service-api-request-handlers/src/index.ts
- components/node-service-api-request-handlers/src/payments/dintero/fetchAuthToken.ts
- components/node-service-api-request-handlers/src/payments/dintero/handlers.ts
- components/node-service-api-request-handlers/src/payments/dintero/types.ts
| Branch?       | main / feature/dintero-payment
| Fixed tickets | [sc-10944]
> dintero payment integration

- components/node-service-api-request-handlers/package.json
- components/node-service-api-request-handlers/src/payments/dintero/handlers.ts
- components/node-service-api-request-handlers/src/payments/dintero/types.ts
| Branch?       | main / dintero-qa
| Bug fix?      | yes
| Fixed tickets | [sc-11025]
> dintero upgrades

- components/node-service-api-request-handlers/package.json
- components/node-service-api-request-handlers/src/payments/dintero/handlers.ts
- components/node-service-api-request-handlers/src/payments/dintero/types.ts
| Branch?       | main /  feature/dintero-express-checkout
> add dintero express checkout

- .github/workflows/gh-pages-preview.yaml
- .github/workflows/gh-pages.yaml
- .github/workflows/main-ci.yaml
- components/js-api-client/README.md
- components/js-api-client/package.json
- components/js-api-client/src/core/client.ts
- components/js-api-client/src/core/massCallClient.ts
- components/js-api-client/tests/call.test.js
- components/js-api-client/tests/catalogue.test.js
- package.json
- yarn.lock
| Branch?       | main / x.y.z |
| Bug fix?      | yes/no       |
| New feature?  | yes/no       |
| BC breaks?    | yes/no       |
| Fixed tickets | #...         |
> feat(js-api-client): cart api and TSUP updates

- components/schema/src/item/components/index.ts
- components/schema/src/item/components/piece/index.ts
- components/schema/src/shape/components.ts
- components/schema/src/shape/enums.ts
| Branch?       | main |
| Bug fix?      | sort of?       |
| New feature?  | sort of?       |
| BC breaks?    | no       |
| Fixed tickets | #        |
> Add piece to @crystallize/schema

- components/reactjs-components/src/content-transformer/component.tsx
| Branch?       | main |
| Bug fix?      | no       |
| New feature?  | no       |
| BC breaks?    | no       |
| Fixed tickets | - |
This PR is only related to TS types. Shouldn't affect any functionality, but improve type safety.
> chore(reactjs-components): cleanup JSX types and fix wrongly typed arguments
